### ISSUE TITLE
Cannot instantiate interface Psr\Http\Client\ClientInterface

### ISSUE THREAD

**Issue by Vahagn-99** [wimski/laravel-psr-http#1]
if (app()->environment('local')) {
            $this->cdek = new \CdekSDK2\Client(new ClientInterface, env('cdek_TEST_ACCOUNT'), env('cdek_TEST_SECURE_PASSWORD'));
            $this->cdek->setTest(true);
        } else {
            $this->cdek = new \CdekSDK2\Client(new ClientInterface, env('cdek_ACCOUNT'), env('cdek_TEST_SECURE_PASSWORD'));
        }
        return $this->cdek;

when i 'm trying to pass interface as parameter i get the above error

**Comment by wimski** [comment]
That is correct. Interfaces are by nature not instantiable.
